<?php

namespace Puf\Core;

class Compilation
{
    private $cssDir;
    private $outputFile;

    public function __construct($config)
    {
        $this->cssDir = realpath(__DIR__ . '/../../../' . $config['compilation']['css_directory'])
            ?: __DIR__ . '/../../../' . $config['compilation']['css_directory'];

        $this->outputFile = "{$this->cssDir}/style.css";

    }

    public function compile()
    {
        if (!$this->cssDir || !is_dir($this->cssDir)) {
            throw new \Exception("CSS directory not found: " . $this->cssDir);
        }

        $compiledCss = "/*\n"
            . "  🚀 Compiled Stylesheet 🚀\n"
            . "  This file is auto-generated. DO NOT edit this file directly.\n"
            . "  Instead, edit individual CSS files in the CSS directory.\n"
            . "*/\n\n";

        $cssFiles = glob($this->cssDir . '/*.css');

        foreach ($cssFiles as $file) {
            if (basename($file) !== 'style.css') {
                $compiledCss .= "/* File: " . basename($file) . " */\n";
                $compiledCss .= file_get_contents($file) . "\n\n";
            }
        }

        file_put_contents($this->outputFile, $compiledCss);
    }
}
